create table if not exists public.system_check_runs (
  id bigint generated by default as identity primary key,
  started_by uuid not null references auth.users(id) on delete restrict,
  source text not null,
  status text not null check (status in ('running', 'success', 'failed')),
  ok boolean,
  checks_total integer not null default 0 check (checks_total >= 0),
  checks_passed integer not null default 0 check (checks_passed >= 0),
  checks_failed integer not null default 0 check (checks_failed >= 0),
  summary jsonb not null default '{}'::jsonb,
  error text,
  started_at timestamp with time zone not null default now(),
  finished_at timestamp with time zone
);

create table if not exists public.system_check_results (
  id bigint generated by default as identity primary key,
  run_id bigint not null references public.system_check_runs(id) on delete cascade,
  check_key text not null,
  severity text not null check (severity in ('info', 'warning', 'critical')),
  ok boolean not null,
  rows_count integer not null default 0 check (rows_count >= 0),
  sample jsonb not null default '[]'::jsonb,
  details jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now()
);

create index if not exists idx_system_check_runs_started_at_desc
  on public.system_check_runs (started_at desc);

create index if not exists idx_system_check_results_run_id_id
  on public.system_check_results (run_id, id);

create index if not exists idx_system_check_results_run_id_ok
  on public.system_check_results (run_id, ok);

alter table public.system_check_runs enable row level security;
alter table public.system_check_results enable row level security;

revoke all on public.system_check_runs from public, anon, authenticated;
revoke all on public.system_check_results from public, anon, authenticated;

select pg_notify('pgrst', 'reload schema');